# Generated by Django 5.2.8 on 2025-11-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emp_id', models.IntegerField(unique=True)),
                ('roles', models.JSONField(default=list)),
                ('pin', models.IntegerField(max_length=4)),
            ],
        ),
    ]
