# Generated by Django 5.2.8 on 2026-01-13 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('pin', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emp_id', models.IntegerField(unique=True)),
                ('roles', models.JSONField(default=list)),
                ('pin', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(db_index=True, help_text='Model number (e.g., EICS112)', max_length=100)),
                ('part_no', models.CharField(db_index=True, help_text='Part number (e.g., EICS112_Part)', max_length=100)),
                ('form_image', models.ImageField(blank=True, help_text='Main form image for this model-part combination', null=True, upload_to='procedure_images/')),
                ('part_image', models.ImageField(blank=True, help_text='Part-specific image', null=True, upload_to='part_images/')),
                ('qc_video', models.FileField(blank=True, help_text='QC video file', null=True, upload_to='qc_videos/')),
                ('testing_video', models.FileField(blank=True, help_text='Testing video file', null=True, upload_to='testing_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Part',
                'verbose_name_plural': 'Model Parts',
                'ordering': ['-created_at'],
                'unique_together': {('model_no', 'part_no')},
            },
        ),
        migrations.CreateModel(
            name='PartProcedureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_config', models.JSONField(default=dict, help_text='Stores all procedure details including sections, custom fields, and checkboxes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_part', models.OneToOneField(help_text='Link to the ModelPart record', on_delete=django.db.models.deletion.CASCADE, related_name='procedure_detail', to='api.modelpart')),
            ],
            options={
                'verbose_name': 'Part Procedure Detail',
                'verbose_name_plural': 'Part Procedure Details',
                'db_table': 'part_procedure_detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(db_index=True, help_text='Part number', max_length=100)),
                ('date', models.DateField(db_index=True, help_text='Date for which the counter is valid')),
                ('counter', models.IntegerField(default=0, help_text='Daily counter for this part (increments for each USID generated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'USID Counter',
                'verbose_name_plural': 'USID Counters',
                'db_table': 'usid_counter',
                'ordering': ['-date', 'part_no'],
                'unique_together': {('part_no', 'date')},
            },
        ),
    ]
