# Generated by Django 5.2.8 on 2026-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
