# Generated by Django 5.2.8 on 2025-11-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(db_index=True, max_length=100)),
                ('part_no', models.CharField(db_index=True, max_length=100)),
                ('form_image', models.ImageField(blank=True, null=True, upload_to='procedure_images/')),
                ('qc_video', models.FileField(blank=True, null=True, upload_to='qc_videos/')),
                ('testing_video', models.FileField(blank=True, null=True, upload_to='testing_videos/')),
                ('has_smd', models.BooleanField(default=False, verbose_name='SMD')),
                ('has_leaded', models.BooleanField(default=False, verbose_name='Leaded')),
                ('has_prod_qc', models.BooleanField(default=False, verbose_name='Production QC')),
                ('has_qc', models.BooleanField(default=False, verbose_name='QC')),
                ('has_testing', models.BooleanField(default=False, verbose_name='Testing')),
                ('has_glueing', models.BooleanField(default=False, verbose_name='Glueing')),
                ('has_cleaning', models.BooleanField(default=False, verbose_name='Cleaning')),
                ('has_spraying', models.BooleanField(default=False, verbose_name='Spraying')),
                ('has_dispatch', models.BooleanField(default=False, verbose_name='Dispatch')),
                ('testing_mode', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Testing Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part Procedure',
                'verbose_name_plural': 'Part Procedures',
                'db_table': 'part_procedure',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_no', 'part_no'], name='part_proced_model_n_739d9e_idx'), models.Index(fields=['model_no'], name='part_proced_model_n_bc71eb_idx')],
                'unique_together': {('model_no', 'part_no')},
            },
        ),
    ]
