# Generated by Django 5.2.8 on 2026-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Admin')], default=1),
        ),
    ]
