# Generated by Django 5.2.8 on 2025-11-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_partprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(db_index=True, help_text='Model number (e.g., EICS112)', max_length=100)),
                ('part_no', models.CharField(db_index=True, help_text='Part number (e.g., EICS112_Part)', max_length=100)),
                ('form_image', models.ImageField(blank=True, help_text='Main form image for this model-part combination', null=True, upload_to='procedure_images/')),
                ('part_image', models.ImageField(blank=True, help_text='Part-specific image', null=True, upload_to='part_images/')),
                ('qc_video', models.FileField(blank=True, help_text='QC video file', null=True, upload_to='qc_videos/')),
                ('testing_video', models.FileField(blank=True, help_text='Testing video file', null=True, upload_to='testing_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Part',
                'verbose_name_plural': 'Model Parts',
                'db_table': 'model_part',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartProcedureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_config', models.JSONField(default=dict, help_text='Stores all procedure details including SMD, QC, Testing, etc. with their sub-procedures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part Procedure Detail',
                'verbose_name_plural': 'Part Procedure Details',
                'db_table': 'part_procedure_detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartProcedureWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_smd', models.BooleanField(default=False, verbose_name='SMD')),
                ('has_leaded', models.BooleanField(default=False, verbose_name='Leaded')),
                ('has_prod_qc', models.BooleanField(default=False, verbose_name='Production QC')),
                ('has_qc', models.BooleanField(default=False, verbose_name='QC')),
                ('has_testing', models.BooleanField(default=False, verbose_name='Testing')),
                ('has_glueing', models.BooleanField(default=False, verbose_name='Glueing')),
                ('has_cleaning', models.BooleanField(default=False, verbose_name='Cleaning')),
                ('has_spraying', models.BooleanField(default=False, verbose_name='Spraying')),
                ('has_dispatch', models.BooleanField(default=False, verbose_name='Dispatch')),
                ('testing_mode', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Testing Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part Procedure Workflow',
                'verbose_name_plural': 'Part Procedure Workflows',
                'db_table': 'part_procedure_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PartProcedure',
        ),
        migrations.AddIndex(
            model_name='modelpart',
            index=models.Index(fields=['model_no'], name='model_part_model_n_1086c2_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpart',
            index=models.Index(fields=['part_no'], name='model_part_part_no_f910cb_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpart',
            index=models.Index(fields=['model_no', 'part_no'], name='model_part_model_n_96289a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelpart',
            unique_together={('model_no', 'part_no')},
        ),
        migrations.AddField(
            model_name='partproceduredetail',
            name='model_part',
            field=models.OneToOneField(help_text='Link to the ModelPart record', on_delete=django.db.models.deletion.CASCADE, related_name='procedure_detail', to='api.modelpart'),
        ),
        migrations.AddField(
            model_name='partprocedureworkflow',
            name='model_part',
            field=models.OneToOneField(help_text='Link to the ModelPart record', on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='api.modelpart'),
        ),
    ]
