# Generated by Django 5.2.8 on 2025-11-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modelpart_partproceduredetail_partprocedureworkflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_sections', models.JSONField(default=list, help_text="List of section names that are enabled/checked (e.g., ['smd', 'qc', 'testing'])")),
                ('section_data', models.JSONField(default=dict, help_text='Stores data rows for each enabled section. Users will fill this data later.')),
                ('testing_mode', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Testing Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_part', models.OneToOneField(help_text='Link to the ModelPart record', on_delete=django.db.models.deletion.CASCADE, related_name='data_table', to='api.modelpart')),
            ],
            options={
                'verbose_name': 'Part Data Table',
                'verbose_name_plural': 'Part Data Tables',
                'db_table': 'part_data_tables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PartProcedureWorkflow',
        ),
        migrations.AddIndex(
            model_name='partdatatable',
            index=models.Index(fields=['model_part'], name='part_data_t_model_p_4c9f59_idx'),
        ),
    ]
