# Generated by Django 5.2.8 on 2025-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_partdatatable_delete_partprocedureworkflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='modelpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partproceduredetail',
            name='model_part',
        ),
        migrations.DeleteModel(
            name='PartDataTable',
        ),
        migrations.DeleteModel(
            name='ModelPart',
        ),
        migrations.DeleteModel(
            name='PartProcedureDetail',
        ),
    ]
