# Generated by Django 5.2.8 on 2025-12-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productionprocedure_alter_modelpart_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(db_index=True, help_text='Model number (e.g., EICS112)', max_length=100)),
                ('part_no', models.CharField(db_index=True, help_text='Part number (e.g., EICS112_Part)', max_length=100)),
                ('form_image', models.ImageField(blank=True, help_text='Main form image for this model-part combination', null=True, upload_to='procedure_images/')),
                ('part_image', models.ImageField(blank=True, help_text='Part-specific image', null=True, upload_to='part_images/')),
                ('qc_video', models.FileField(blank=True, help_text='QC video file', null=True, upload_to='qc_videos/')),
                ('testing_video', models.FileField(blank=True, help_text='Testing video file', null=True, upload_to='testing_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Part',
                'verbose_name_plural': 'Model Parts',
                'ordering': ['-created_at'],
                'unique_together': {('model_no', 'part_no')},
            },
        ),
        migrations.CreateModel(
            name='PartProcedureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_config', models.JSONField(default=dict, help_text='Stores all procedure details including sections, custom fields, and checkboxes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_part', models.OneToOneField(help_text='Link to the ModelPart record', on_delete=django.db.models.deletion.CASCADE, related_name='procedure_detail', to='api.modelpart')),
            ],
            options={
                'verbose_name': 'Part Procedure Detail',
                'verbose_name_plural': 'Part Procedure Details',
                'db_table': 'part_procedure_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
