from django.urls import path
from .views import (
    UserDetailView, UserListCreateView, UserLoginView, AdminLoginView, AdminLogoutView, 
    AdminProfileView, UserProfileView, ProductionProcedureCreateView, ModelPartListView,
    ProcedureDetailView, DashboardStatsView, DashboardChartDataView, UserModelListView,
    UserModelPartsView, UserPartSectionsView, KitVerificationView, SMDDataFetchView, SMDUpdateView,
    SMDQCDataFetchView, SMDQCUpdateView, PreFormingQCDataFetchView, PreFormingQCUpdateView,
    LeadedQCDataFetchView, LeadedQCUpdateView, ProdQCDataFetchView, ProdQCUpdateView,
    AccessoriesPackingDataFetchView, AccessoriesPackingUpdateView, QCProcedureConfigView,
    TestingProcedureConfigView, DispatchProcedureConfigView, DispatchSONumbersView, USIDGenerateView, QCSubmitView, TestingSubmitView, SerialNumberStatusView, TestingSerialNumberSearchView,
    HeatRunSerialNumberSearchView, HeatRunSubmitView, CleaningSerialNumberSearchView, CleaningSubmitView,
    GlueingSerialNumberSearchView, GlueingSubmitView, SprayingSerialNumberSearchView, SprayingSubmitView,
    DispatchSerialNumberSearchView
)

urlpatterns = [
    path('users/', UserListCreateView.as_view(), name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/login/', UserLoginView.as_view(), name='user-login'),
    path('user/models/', UserModelListView.as_view(), name='user-models'),
    path('user/models/<str:model_no>/parts/', UserModelPartsView.as_view(), name='user-model-parts'),
    path('user/parts/<str:part_no>/sections/', UserPartSectionsView.as_view(), name='user-part-sections'),
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('admin/profile/', AdminProfileView.as_view(), name='admin-profile'),
    path('user/profile/', UserProfileView.as_view(), name='user-profile'),
    path('production-procedure/', ProductionProcedureCreateView.as_view(), name='production-procedure-create'),
    path('model-parts/', ModelPartListView.as_view(), name='model-part-list'),
    path('procedure-detail/<str:model_no>/', ProcedureDetailView.as_view(), name='procedure-detail'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard-stats'),
    path('dashboard/charts/', DashboardChartDataView.as_view(), name='dashboard-charts'),
    path('kit-verification/', KitVerificationView.as_view(), name='kit-verification'),
    path('smd-data-fetch/', SMDDataFetchView.as_view(), name='smd-data-fetch'),
    path('smd-update/', SMDUpdateView.as_view(), name='smd-update'),
    path('smd-qc-data-fetch/', SMDQCDataFetchView.as_view(), name='smd-qc-data-fetch'),
    path('smd-qc-update/', SMDQCUpdateView.as_view(), name='smd-qc-update'),
    path('pre-forming-qc-data-fetch/', PreFormingQCDataFetchView.as_view(), name='pre-forming-qc-data-fetch'),
    path('pre-forming-qc-update/', PreFormingQCUpdateView.as_view(), name='pre-forming-qc-update'),
    path('leaded-qc-data-fetch/', LeadedQCDataFetchView.as_view(), name='leaded-qc-data-fetch'),
    path('leaded-qc-update/', LeadedQCUpdateView.as_view(), name='leaded-qc-update'),
    path('prod-qc-data-fetch/', ProdQCDataFetchView.as_view(), name='prod-qc-data-fetch'),
    path('prod-qc-update/', ProdQCUpdateView.as_view(), name='prod-qc-update'),
    path('accessories-packing-data-fetch/', AccessoriesPackingDataFetchView.as_view(), name='accessories-packing-data-fetch'),
    path('accessories-packing-update/', AccessoriesPackingUpdateView.as_view(), name='accessories-packing-update'),
    path('qc-procedure-config/<str:part_no>/', QCProcedureConfigView.as_view(), name='qc-procedure-config'),
    path('testing-procedure-config/<str:part_no>/', TestingProcedureConfigView.as_view(), name='testing-procedure-config'),
    path('dispatch-procedure-config/<str:part_no>/', DispatchProcedureConfigView.as_view(), name='dispatch-procedure-config'),
    path('dispatch-so-numbers/<str:part_no>/', DispatchSONumbersView.as_view(), name='dispatch-so-numbers'),
    path('usid-generate/', USIDGenerateView.as_view(), name='usid-generate'),
    path('qc-submit/', QCSubmitView.as_view(), name='qc-submit'),
    path('testing-submit/', TestingSubmitView.as_view(), name='testing-submit'),
    path('heat-run-submit/', HeatRunSubmitView.as_view(), name='heat-run-submit'),
    path('cleaning-submit/', CleaningSubmitView.as_view(), name='cleaning-submit'),
    path('glueing-submit/', GlueingSubmitView.as_view(), name='glueing-submit'),
    path('spraying-submit/', SprayingSubmitView.as_view(), name='spraying-submit'),
    path('serial-number-status/', SerialNumberStatusView.as_view(), name='serial-number-status'),
    path('testing-serial-number-search/', TestingSerialNumberSearchView.as_view(), name='testing-serial-number-search'),
    path('heat-run-serial-number-search/', HeatRunSerialNumberSearchView.as_view(), name='heat-run-serial-number-search'),
    path('cleaning-serial-number-search/', CleaningSerialNumberSearchView.as_view(), name='cleaning-serial-number-search'),
    path('glueing-serial-number-search/', GlueingSerialNumberSearchView.as_view(), name='glueing-serial-number-search'),
    path('spraying-serial-number-search/', SprayingSerialNumberSearchView.as_view(), name='spraying-serial-number-search'),
    path('dispatch-serial-number-search/', DispatchSerialNumberSearchView.as_view(), name='dispatch-serial-number-search'),
]